version: '3.8'

services:
  bazaar-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bazaar_app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      JWT_SIGNATURE: ${JWT_SIGNATURE}
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      - db
    networks:
      - bazaar-network

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bazaar-network

networks:
  bazaar-network:
    driver: bridge

volumes:
  postgres_data:
