// Code generated by MockGen. DO NOT EDIT.
// Source: seller.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2025_1_ChillGuys/internal/models"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockISellerUsecase is a mock of ISellerUsecase interface.
type MockISellerUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockISellerUsecaseMockRecorder
}

// MockISellerUsecaseMockRecorder is the mock recorder for MockISellerUsecase.
type MockISellerUsecaseMockRecorder struct {
	mock *MockISellerUsecase
}

// NewMockISellerUsecase creates a new mock instance.
func NewMockISellerUsecase(ctrl *gomock.Controller) *MockISellerUsecase {
	mock := &MockISellerUsecase{ctrl: ctrl}
	mock.recorder = &MockISellerUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISellerUsecase) EXPECT() *MockISellerUsecaseMockRecorder {
	return m.recorder
}

// AddProduct mocks base method.
func (m *MockISellerUsecase) AddProduct(ctx context.Context, product *models.Product, categoryID uuid.UUID) (*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProduct", ctx, product, categoryID)
	ret0, _ := ret[0].(*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddProduct indicates an expected call of AddProduct.
func (mr *MockISellerUsecaseMockRecorder) AddProduct(ctx, product, categoryID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProduct", reflect.TypeOf((*MockISellerUsecase)(nil).AddProduct), ctx, product, categoryID)
}

// CheckProductBelongs mocks base method.
func (m *MockISellerUsecase) CheckProductBelongs(ctx context.Context, productID, sellerID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckProductBelongs", ctx, productID, sellerID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckProductBelongs indicates an expected call of CheckProductBelongs.
func (mr *MockISellerUsecaseMockRecorder) CheckProductBelongs(ctx, productID, sellerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckProductBelongs", reflect.TypeOf((*MockISellerUsecase)(nil).CheckProductBelongs), ctx, productID, sellerID)
}

// GetSellerProducts mocks base method.
func (m *MockISellerUsecase) GetSellerProducts(ctx context.Context, sellerID uuid.UUID, offset int) ([]*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSellerProducts", ctx, sellerID, offset)
	ret0, _ := ret[0].([]*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSellerProducts indicates an expected call of GetSellerProducts.
func (mr *MockISellerUsecaseMockRecorder) GetSellerProducts(ctx, sellerID, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSellerProducts", reflect.TypeOf((*MockISellerUsecase)(nil).GetSellerProducts), ctx, sellerID, offset)
}

// UploadProductImage mocks base method.
func (m *MockISellerUsecase) UploadProductImage(ctx context.Context, productID uuid.UUID, imageURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadProductImage", ctx, productID, imageURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadProductImage indicates an expected call of UploadProductImage.
func (mr *MockISellerUsecaseMockRecorder) UploadProductImage(ctx, productID, imageURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadProductImage", reflect.TypeOf((*MockISellerUsecase)(nil).UploadProductImage), ctx, productID, imageURL)
}
