{
 "title": "Bazaar Services Monitoring",
 "description": "Comprehensive dashboard for all Bazaar microservices",
 "tags": [
  "bazaar",
  "monitoring",
  "microservices"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "service", "label": "Service", "query": ".*,auth,user,review,bazaar" }
  ]
 },
 "panels": [
  {
   "title": "Bazaar - Error Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(Url, Method, StatusCode) (rate(bazaar_app_errors_total[5m])) \n/ \nsum by(Url, Method, StatusCode) (rate(bazaar_app_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Auth Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Auth - Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(auth_service_requests_total)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Auth - Response Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(auth_service_duration_seconds_sum[5m])) by (Url)\n/ \nsum(rate(auth_service_duration_seconds_count[5m])) by (Url)  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auth - Top Endpoints",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "topk(\n  5,\n  sum by(Url) (\n    rate(auth_service_duration_seconds_count[1h])\n  )\n) "
    }
   ]
  },
  {
   "title": "Auth - CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "targets": [
    { "expr": "auth_service_cpu_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Auth - Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "auth_service_memory_usage_bytes / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auth - Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "auth_service_disk_usage_percent",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "User Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "User - Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "legendFormat": "Total" }
   ]
  },
  {
   "title": "User - Response Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(user_service_duration_seconds_sum[5m])) by (Url) \n/ \nsum(rate(user_service_duration_seconds_count[5m])) by (Url)  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User - Top Endpoints",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "topk(5, sum by (Url) (rate(user_service_duration_seconds_count[1h]))) "
    }
   ]
  },
  {
   "title": "User - CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
   "targets": [
    { "expr": "user_service_cpu_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "User - Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "user_service_memory_usage_bytes / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User - Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "user_service_disk_usage_percent",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Review Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Review - Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(review_service_requests_total) ",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Review - Response Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(review_service_duration_seconds_sum[5m])) by (Url) \n/ \nsum(rate(review_service_duration_seconds_count[5m])) by (Url) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Review - Top Endpoints",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "topk(\n  5,\n  sum by(Url) (\n    rate(review_service_duration_seconds_count[1h])\n  )\n)"
    }
   ]
  },
  {
   "title": "Review - CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "review_service_cpu_usage_percent",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Review - Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "review_service_memory_usage_bytes / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Review - Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "expr": "review_service_disk_usage_percent",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Bazaar-App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Bazaar - Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(bazaar_app_requests_total)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Bazaar - Response Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(bazaar_app_duration_seconds_sum{Url=~'/api/v1/.*'}[5m])) by (Url)\n/ \nsum(rate(bazaar_app_duration_seconds_count{Url=~'/api/v1/.*'}[5m])) by (Url)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bazaar - Top Endpoints",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "topk(5, sum by (Url) (rate(bazaar_app_duration_seconds_count{Url=~'/api/v1/.*'}[1h]))) "
    }
   ]
  },
  {
   "title": "Bazaar-CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 77 },
   "targets": [
    { "expr": "bazaar_app_cpu_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bazaar - Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "bazaar_app_memory_usage_bytes / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bazaar - Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "targets": [
    { "expr": "bazaar_app_disk_usage_percent", "legendFormat": "__auto" }
   ]
  }
 ]
}