basePath: /api
definitions:
  models.Product:
    properties:
      description:
        type: string
      id:
        type: string
      name:
        type: string
      preview_image_url:
        type: string
      price:
        type: integer
      quantity:
        type: integer
      rating:
        type: integer
      reviews_count:
        description: Добавлено поле
        type: integer
      seller_id:
        type: string
      status:
        type: string
      updated_at:
        type: string
    type: object
  models.User:
    properties:
      email:
        type: string
      id:
        type: string
      imageURL:
        type: string
      name:
        type: string
      phoneNumber:
        type: string
      surname:
        type: string
    type: object
  models.UserLoginRequestDTO:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.UserRegisterRequestDTO:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      surname:
        type: string
    type: object
  response.ErrorResponse:
    properties:
      message:
        type: string
    type: object
host: 90.156.217.63:8081
info:
  contact: {}
  description: API for ChillGuys marketplace
  title: ChillGuys API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Авторизация пользователя
      parameters:
      - description: User credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.UserLoginRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: No Content
          headers:
            Set-Cookie:
              description: Устанавливает JWT-токен в куки
              type: string
          schema:
            type: ""
        "400":
          description: Ошибка валидации
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "401":
          description: Неверные email или пароль
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Login user
      tags:
      - auth
  /auth/logout:
    post:
      description: Выход пользователя
      responses:
        "200":
          description: No Content
          schema:
            type: ""
        "401":
          description: Пользователь не найден
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - TokenAuth: []
      summary: Logout user
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Создает нового пользователя, хеширует пароль и устанавливает JWT-токен
        в куки
      parameters:
      - description: Данные для регистрации
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.UserRegisterRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: No Content
          headers:
            Set-Cookie:
              description: Устанавливает JWT-токен в куки
              type: string
          schema:
            type: ""
        "400":
          description: Некорректный запрос
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "409":
          description: Пользователь уже существует
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Register user
      tags:
      - auth
  /files/{objectID}:
    get:
      description: Возвращает URL для доступа к файлу в MinIO
      parameters:
      - description: ID объекта в MinIO
        in: path
        name: objectID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Ссылка на файл
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Неверный ID объекта
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Файл не найден
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Получить файл по ID
      tags:
      - files
  /products/:
    get:
      description: Возвращает список всех продуктов
      produces:
      - application/json
      responses:
        "200":
          description: Список продуктов
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Получить все продукты
      tags:
      - products
  /products/{id}:
    get:
      description: Возвращает продукт по его ID
      parameters:
      - description: ID продукта
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Информация о продукте
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: Некорректный ID
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Продукт не найден
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Получить продукт по ID
      tags:
      - products
  /products/{id}/cover:
    get:
      description: Возвращает обложку продукта по его ID
      parameters:
      - description: ID продукта
        in: path
        name: id
        required: true
        type: integer
      produces:
      - image/jpeg
      responses:
        "200":
          description: Обложка продукта
          schema:
            type: file
        "400":
          description: Некорректный ID
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Обложка не найдена
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Получить обложку продукта
      tags:
      - products
  /products/upload:
    post:
      consumes:
      - multipart/form-data
      description: Загружает один файл в хранилище MinIO
      parameters:
      - description: Файл для загрузки
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Информация о загруженном файле
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Ошибка в запросе
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Загрузить файл в MinIO
      tags:
      - products
  /users/avatar:
    post:
      consumes:
      - multipart/form-data
      description: Загружает аватар пользователя
      parameters:
      - description: Файл изображения
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: URL загруженного аватара
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Ошибка при обработке формы
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Ошибка загрузки файла
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - TokenAuth: []
      summary: Upload avatar
      tags:
      - users
  /users/me:
    get:
      description: Получение информации о текущем пользователе
      produces:
      - application/json
      responses:
        "200":
          description: Информация о пользователе
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Некорректный запрос
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "401":
          description: Пользователь не найден
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - TokenAuth: []
      summary: Get user info
      tags:
      - users
securityDefinitions:
  BasicAuth:
    type: basic
  TokenAuth:
    in: cookie
    name: token
    type: apiKey
swagger: "2.0"
