basePath: /api
definitions:
  github_com_go-park-mail-ru_2025_1_ChillGuys_internal_models.BasketItem:
    properties:
      basket_id:
        type: string
      id:
        type: string
      price_discount:
        type: number
      product_id:
        type: string
      product_image:
        type: string
      product_name:
        type: string
      product_price:
        type: number
      quantity:
        type: integer
      updated_at:
        type: string
    type: object
  github_com_go-park-mail-ru_2025_1_ChillGuys_internal_models.Category:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  github_com_go-park-mail-ru_2025_1_ChillGuys_internal_models.Product:
    properties:
      description:
        type: string
      id:
        type: string
      name:
        type: string
      preview_image_url:
        type: string
      price:
        type: number
      quantity:
        type: integer
      rating:
        type: integer
      reviews_count:
        type: integer
      seller_id:
        type: string
      status:
        $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_models.ProductStatus'
      updated_at:
        type: string
    type: object
  github_com_go-park-mail-ru_2025_1_ChillGuys_internal_models.ProductStatus:
    enum:
    - 0
    - 1
    - 2
    type: integer
    x-enum-comments:
      ProductApproved: Одобрено
      ProductPending: Ожидает
      ProductRejected: Отказано
    x-enum-varnames:
    - ProductPending
    - ProductRejected
    - ProductApproved
  github_com_go-park-mail-ru_2025_1_ChillGuys_internal_models.User:
    properties:
      email:
        type: string
      id:
        type: string
      imageURL:
        type: string
      name:
        type: string
      phoneNumber:
        type: string
      surname:
        type: string
    type: object
  github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.BasketResponse:
    properties:
      products:
        items:
          $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_models.BasketItem'
        type: array
      total:
        type: integer
      total_price:
        type: number
      total_price_discount:
        type: number
    type: object
  github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.UpdateQuantityRequest:
    properties:
      quantity:
        type: integer
    type: object
  github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.UserRegisterRequestDTO:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      surname:
        type: string
    type: object
host: 90.156.217.63:8081
info:
  contact: {}
  description: API for ChillGuys marketplace
  title: ChillGuys API
  version: "1.0"
paths:
  /api/v1/basket:
    get:
      description: Возвращает все товары в корзине пользователя
      produces:
      - application/json
      responses:
        "200":
          description: Содержимое корзины
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.BasketResponse'
        "401":
          description: Пользователь не авторизован
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
        "404":
          description: Корзина не найдена
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Получить содержимое корзины
      tags:
      - basket
  /api/v1/basket/{id}:
    delete:
      description: Удаляет товар из корзины пользователя
      parameters:
      - description: ID товара
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: Товар успешно удалён
        "400":
          description: Некорректный ID
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
        "401":
          description: Пользователь не авторизован
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
        "404":
          description: Товар не найден в корзине
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Удалить товар из корзины
      tags:
      - basket
    patch:
      consumes:
      - application/json
      description: Изменяет количество указанного товара в корзине
      parameters:
      - description: ID товара
        in: path
        name: id
        required: true
        type: string
      - description: Новое количество
        in: body
        name: quantity
        required: true
        schema:
          $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.UpdateQuantityRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Обновленный товар
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_models.BasketItem'
        "400":
          description: Некорректные данные
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
        "401":
          description: Пользователь не авторизован
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
        "404":
          description: Товар не найден
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Обновить количество товара
      tags:
      - basket
    post:
      description: Добавляет товар в корзину пользователя или увеличивает количество,
        если товар уже есть
      parameters:
      - description: ID товара
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Добавленный товар
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_models.BasketItem'
        "400":
          description: Некорректный ID
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
        "401":
          description: Пользователь не авторизован
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
        "404":
          description: Товар не найден
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Добавить товар в корзину
      tags:
      - basket
  /api/v1/products/category/{id}:
    get:
      description: Возвращает список всех одобренных товаров, принадлежащих указанной
        категории.
      parameters:
      - description: UUID категории в формате строки
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Успешный запрос. Возвращает массив товаров.
          schema:
            items:
              $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_models.Product'
            type: array
        "400":
          description: Неверный формат UUID категории
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
        "404":
          description: Категория не найдена
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
      summary: Получить товары по категории
      tags:
      - products
  /auth/logout:
    post:
      description: Выход пользователя
      responses:
        "200":
          description: No Content
          schema:
            type: ""
        "401":
          description: Пользователь не найден
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
      security:
      - TokenAuth: []
      summary: Logout user
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Создает нового пользователя, хеширует пароль и устанавливает JWT-токен
        в куки
      parameters:
      - description: Данные для регистрации
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.UserRegisterRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: No Content
          headers:
            Set-Set:
              description: Устанавливает JWT-токен в куки
              type: string
          schema:
            type: ""
        "400":
          description: Некорректный запрос
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
        "409":
          description: Пользователь уже существует
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
      summary: Register user
      tags:
      - auth
  /basket:
    delete:
      description: Полностью удаляет все товары из корзины пользователя
      responses:
        "204":
          description: Корзина успешно очищена
        "401":
          description: Пользователь не авторизован
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Очистить корзину
      tags:
      - basket
  /categories:
    get:
      description: Возвращает список всех доступных категорий товаров
      produces:
      - application/json
      responses:
        "200":
          description: Список категорий
          schema:
            items:
              $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_models.Category'
            type: array
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
      summary: Получить все категории
      tags:
      - categories
  /files/{objectID}:
    get:
      description: Возвращает URL для доступа к файлу в MinIO
      parameters:
      - description: ID объекта в MinIO
        in: path
        name: objectID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Ссылка на файл
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Неверный ID объекта
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
        "404":
          description: Файл не найден
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
      summary: Получить файл по ID
      tags:
      - files
  /products:
    get:
      description: Возвращает список всех продуктов
      produces:
      - application/json
      responses:
        "200":
          description: Список продуктов
          schema:
            items:
              $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_models.Product'
            type: array
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
      summary: Получить все продукты
      tags:
      - products
  /products/{id}:
    get:
      description: Возвращает продукт по его ID
      parameters:
      - description: ID продукта
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Информация о продукте
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_models.Product'
        "400":
          description: Некорректный ID
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
        "404":
          description: Продукт не найден
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
      summary: Получить продукт по ID
      tags:
      - products
  /products/upload:
    post:
      consumes:
      - multipart/form-data
      description: Загружает один файл в хранилище MinIO
      parameters:
      - description: Файл для загрузки
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Информация о загруженном файле
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Ошибка в запросе
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
      summary: Загрузить файл в MinIO
      tags:
      - products
  /users/avatar:
    post:
      consumes:
      - multipart/form-data
      description: Загружает аватар пользователя
      parameters:
      - description: Файл изображения
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: URL загруженного аватара
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Ошибка при обработке формы
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
        "500":
          description: Ошибка загрузки файла
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
      security:
      - TokenAuth: []
      summary: Upload avatar
      tags:
      - users
  /users/me:
    get:
      description: Получение информации о текущем пользователе
      produces:
      - application/json
      responses:
        "200":
          description: Информация о пользователе
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_models.User'
        "400":
          description: Некорректный запрос
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
        "401":
          description: Пользователь не найден
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/github_com_go-park-mail-ru_2025_1_ChillGuys_internal_transport_dto.ErrorResponse'
      security:
      - TokenAuth: []
      summary: Get user info
      tags:
      - users
securityDefinitions:
  BasicAuth:
    type: basic
  TokenAuth:
    in: cookie
    name: token
    type: apiKey
swagger: "2.0"
