name: Build, Push and Deploy
on:
  push:
    branches:
      - main
      - develop

env:
  REGISTRY: "niknike"

jobs:
  build-and-push:
    name: Build and push images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.REGISTRY }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build images with compose
        run: |
          docker compose build
      
      - name: Tag and push images
        run: |          
          docker push ${{ env.REGISTRY }}/bazaar:latest
          docker push ${{ env.REGISTRY }}/user-service:latest
          docker push ${{ env.REGISTRY }}/auth-service:latest
          docker push ${{ env.REGISTRY }}/review-service:latest
          docker push ${{ env.REGISTRY }}/csat-service:latest

  deploy:
    name: Deploy services
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.VM_KEY }}
          script: |
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ env.REGISTRY }} --password-stdin
            docker-compose down
            docker-compose pull
            docker-compose up -d